spring:
  datasource:
    url: jdbc:mariadb://192.168.0.128:3306/board_db
    username: moon
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
